package org.openmrs.module.pihcore.config;

public class Components {

        public static final String VISIT_MANAGEMENT = "visitManagement";
        public static final String ACTIVE_VISITS = "activeVisits";
        public static final String CHECK_IN = "checkIn";
        public static final String CHECK_IN_HOMEPAGE_APP = "checkInHomepageApp";
        public static final String UHM_VITALS = "uhmVitals";
        public static final String VITALS = "vitals";
        public static final String CONSULT = "consult";
        public static final String ED_CONSULT = "edConsult";
        public static final String ADT = "adt";
        public static final String DEATH_CERTIFICATE = "deathCertificate";
        public static final String RADIOLOGY = "radiology";
        public static final String DISPENSING = "dispensing";
        public static final String SURGERY = "surgery";
        public static final String ONCOLOGY = "oncology";
        public static final String NCD = "ncd";
        public static final String HIV = "hiv";
        public static final String VCT = "vct";
        public static final String MENTAL_HEALTH = "mentalHealth";
        public static final String MENTAL_HEALTH_PROGRAM = "mentalHealthProgam";
        public static final String SOCIO_ECONOMICS= "socioEconomics";
        public static final String LAB_RESULTS = "labResults";
        public static final String OVERVIEW_REPORTS = "overviewReports";
        public static final String MONITORING_REPORTS = "monitoringReports";
        public static final String DATA_EXPORTS = "dataExports";  // enabled the data export section
        public static final String ALL_DATA_EXPORTS = "allDataExports"; // show all data exports, regardless of what components are actually enabled (used by Mirebalais reporting server)
        public static final String ARCHIVES = "archives";
        public static final String WRISTBANDS = "wristbands";
        public static final String APPOINTMENT_SCHEDULING = "appointmentScheduling";
        public static final String SYSTEM_ADMINISTRATION = "systemAdministration";
        public static final String MANAGE_PRINTERS = "managePrinters";
        public static final String MY_ACCOUNT = "myAccount";
        public static final String PATIENT_REGISTRATION = "patientRegistration";
        public static final String CLINICIAN_DASHBOARD = "clinicianDashboard";
        public static final String VISIT_NOTE = "visitNote";
        public static final String ALLERGIES = "allergies";
        public static final String PRESCRIPTIONS = "prescriptions";
        public static final String LEGACY_MPI = "legacyMpi";
        public static final String LACOLLINE_PATIENT_REGISTRATION_ENCOUNTER_TYPES = "lacollinePatientRegistrationEncounterTypes";
        public static final String ID_CARD_PRINTING = "idcardPrinting";
        public static final String CHART_SEARCH = "chartSearch";
        public static final String WAITING_FOR_CONSULT = "waitingForConsult";
        public static final String PRIMARY_CARE = "primaryCare";
        public static final String PACS_INTEGRATION = "pacsIntegration";
        public static final String ED_TRIAGE = "edTriage";
        public static final String ED_TRIAGE_QUEUE = "edTriageQueue";
        public static final String BIOMETRICS_FINGERPRINTS = "biometricsFingerPrints";
        public static final String TODAYS_VISITS = "todaysVisits";
        public static final String LAB_TRACKING = "labTracking";
        public static final String PROGRAMS = "programs";
        public static final String RELATIONSHIPS = "relationships";
        public static final String ZIKA = "zika";
        public static final String EXPORT_PATIENTS = "exportPatients";
        public static final String IMPORT_PATIENTS = "importPatients";
        public static final String PATIENT_DOCUMENTS = "patientDocuments";
        public static final String CHW_APP = "chwApp";
        public static final String CONDITION_LIST = "conditionList";
        public static final String ORDER_ENTRY = "orderEntry";  // TODO we probably want a different name for this?  break up by drug orders and lab orders, etc?
        public static final String COHORT_BUILDER = "cohortBuilder";
}
