name: Check dependencies
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out pihcore module
        uses: actions/checkout@v4
        with:
          path: repository
      - name: Check out PIH tools
        uses: actions/checkout@v4
        with:
          path: tools
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'maven'
      - name: Check dependencies
        id: checkDependencies
        shell: bash
        run: |
          #!/usr/bin/env bash
          set +e
          ./tools/ci/dependency-status-with-repolling.sh -r 300 -d ./repository
          if [ $? -eq 1 ]; then
            gh workflow run deploy.yml
          fi