name: Deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
        server-id: openmrs-repo-modules-pih
        server-username: OPENMRS_MAVEN_USERNAME
        server-password: OPENMRS_MAVEN_PASSWORD

    # Set up git config
    - name: Setup Git Config
      run: |
        git config user.name "Github Action"
        git config user.email "github-action@users.noreply.github.com"

    - name: Update dependencies
      run: |
        mvn clean versions:update-properties -U
        mvn scm:checkin -Dmessage='automatic update of mvn version dependencies'
      env:
        OPENMRS_MAVEN_USERNAME: ${{ secrets.OPENMRS_MAVEN_USERNAME }}
        OPENMRS_MAVEN_PASSWORD: ${{ secrets.OPENMRS_MAVEN_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Maven Deploy
      run: mvn -B deploy --file pom.xml
      env:
        OPENMRS_MAVEN_USERNAME: ${{ secrets.OPENMRS_MAVEN_USERNAME }}
        OPENMRS_MAVEN_PASSWORD: ${{ secrets.OPENMRS_MAVEN_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}