name: Deploy
on:
  push:
    branches: ['master']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
        server-id: openmrs-repo-modules-pih
        server-username: OPENMRS_MAVEN_USERNAME
        server-password: OPENMRS_MAVEN_PASSWORD
    - name: Maven Deploy
      run: mvn -B deploy --file pom.xml
      env:
        OPENMRS_MAVEN_USERNAME: ${{ secrets.OPENMRS_MAVEN_USERNAME }}
        OPENMRS_MAVEN_PASSWORD: ${{ secrets.OPENMRS_MAVEN_PASSWORD }}
    - name: Trigger Distribution Build
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-PIHEMRDISTRIBUTION'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'