name: Build with Maven

on:
  push:
    branches: [ dependency-report ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        java-version: [ 8 ]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    env:
      PLATFORM: ${{ matrix.platform }}
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Update dependency properties
        id: update_dependency_properties
        run: |
          mvn clean versions:update-properties
          mvn net.mekomsolutions.maven.plugin:dependency-tracker-maven-plugin:1.0.0:track -U