name: Update Versions

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  update-versions:
    if: github.repository_owner == 'PIH'
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/update-versions.yml@main
    with:
      allow-snapshots: false
    secrets: inherit
